### ISSUE TITLE
Checklist one

### ISSUE THREAD

**Issue by austinmerritt** [austinmerritt/Fredwin-running#44]
- [ ] New one in GitHub

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha syncing."/>

- [ ] <span data-href="#aha_task_list_FR-25-1" data-version="v2" data-aha="Do not remove this tag. Used for Aha syncing."/> The first thing

- [ ] <span data-href="#aha_task_list_FR-25-2" data-version="v2" data-aha="Do not remove this tag. Used for Aha syncing."/> The second thing
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha syncing."/>

Aha! Link: https://reallybigaha.aha-staging-8.io/features/FR-25
